### ISSUE TITLE
Bug: Compilation error when using subset of languages in v1.7.0

### ISSUE THREAD

**Issue by gezihuzi** [pemistahl/lingua-rs#452]
## Description
After upgrading from lingua-crate v1.6.2 to v1.7.0, I encountered compilation errors when using only a subset of available languages. Specifically, when I only enabled Japanese, the code fails to compile due to issues in the `detect_language_with_unique_and_common_ngrams` function.

## Steps to Reproduce
1. Configure lingua with only Japanese language enabled (disable other languages)
2. Attempt to compile the project
3. Compilation fails when trying to reference languages that are not enabled

## Error Details
The compilation error occurs in this function: https://github.com/pemistahl/lingua-rs/blob/a7ec486d033880d3c1a4f82dacabdd32dd583489/src/detector.rs#L942-L950

When only Japanese is enabled, the compiler fails because the code still tries to reference languages like Hindi and Marathi which are not available in my configuration.

## Environment
- Lingua-crate version: v1.7.0 (upgraded from v1.6.2)
- Languages enabled: Only Japanese
- Rust version: rustc 1.85.1 (4eb161250 2025-03-15)
- OS: Mac OS 15.3.2 [64-bit]

## Suggested Fix
The code should conditionally reference languages based on which ones are enabled in the configuration. This would allow users to enable only a subset of languages without compilation errors.

**Comment by pemistahl** [comment]
Thanks, it's fixed now in release 1.7.1. I'm sorry for the inconvenience. No matter how thorough the programming is, there is always a little detail that is missed.

**Comment by gezihuzi** [comment]
> Thanks, it's fixed now in release 1.7.1. I'm sorry for the inconvenience. No matter how thorough the programming is, there is always a little detail that is missed.

Thank you for the quick fix and releasing version 1.7.1! I appreciate your prompt response and resolution of the issue. No worries at all - completely understandable that small details can be missed. I'm looking forward to using the updated version.
